import { prisma } from '@/lib/prisma'

const SEED_LAWYERS = [
  {
    name: 'Adv. Priya Sharma',
    specialties: ['Family Law'],
    experience: 8,
    location: 'Kathmandu',
    languages: ['Nepali', 'English', 'Hindi'],
    fee: 'NPR 2,000 – 6,000',
    bio: 'Specializes in divorce, child custody, and property disputes within family matters.',
    phone: '+977-9800000001',
    email: 'priya@lawmail.com',
    available: true,
  },
  {
    name: 'Adv. Sushil Acharya',
    specialties: ['Criminal Law'],
    experience: 14,
    location: 'Kathmandu',
    languages: ['Nepali', 'English'],
    fee: 'NPR 5,000 – 15,000',
    bio: 'Experienced in criminal defense, bail hearings, and appellate proceedings across Bagmati courts.',
    phone: '+977-9800000002',
    email: 'sushil@lawmail.com',
    available: true,
  },
  {
    name: 'Adv. Bina Thapa',
    specialties: ['Business Law'],
    experience: 6,
    location: 'Lalitpur',
    languages: ['Nepali', 'English'],
    fee: 'NPR 3,000 – 10,000',
    bio: 'Advises startups and SMEs on company registration, contracts, and compliance with Nepal Company Act.',
    phone: '+977-9800000003',
    email: 'bina@lawmail.com',
    available: true,
  },
  {
    name: 'Adv. Rajan Poudel',
    specialties: ['Property Law'],
    experience: 11,
    location: 'Pokhara',
    languages: ['Nepali'],
    fee: 'NPR 2,000 – 7,000',
    bio: 'Handles land disputes, registration fraud, and property transfer cases in Gandaki Province.',
    phone: '+977-9800000004',
    email: 'rajan@lawmail.com',
    available: true,
  },
  {
    name: 'Adv. Kamala Gurung',
    specialties: ['Labour Law'],
    experience: 9,
    location: 'Kathmandu',
    languages: ['Nepali', 'English'],
    fee: 'NPR 1,500 – 5,000',
    bio: 'Represents workers in wrongful termination, wage disputes, and occupational safety cases.',
    phone: '+977-9800000005',
    email: 'kamala@lawmail.com',
    available: true,
  },
  {
    name: 'Adv. Dipesh Maharjan',
    specialties: ['Tax Law'],
    experience: 7,
    location: 'Lalitpur',
    languages: ['Nepali', 'English'],
    fee: 'NPR 3,000 – 9,000',
    bio: 'Assists businesses with VAT compliance, IRD disputes, and international tax matters.',
    phone: '+977-9800000006',
    email: 'dipesh@lawmail.com',
    available: true,
  },
  {
    name: 'Adv. Sunita Rai',
    specialties: ['Immigration Law'],
    experience: 5,
    location: 'Kathmandu',
    languages: ['Nepali', 'English', 'Japanese'],
    fee: 'NPR 4,000 – 12,000',
    bio: 'Handles visa applications, work permits, citizenship acquisition, and immigration appeals.',
    phone: '+977-9800000007',
    email: 'sunita@lawmail.com',
    available: true,
  },
  {
    name: 'Adv. Prakash Bhattarai',
    specialties: ['Criminal Law'],
    experience: 18,
    location: 'Chitwan',
    languages: ['Nepali', 'English', 'Hindi'],
    fee: 'NPR 4,000 – 12,000',
    bio: 'Senior criminal lawyer with extensive experience in high-profile cases and Supreme Court practice.',
    phone: '+977-9800000008',
    email: 'prakash@lawmail.com',
    available: true,
  },
  {
    name: 'Adv. Roshan Shahi',
    specialties: ['Human Rights Law'],
    experience: 10,
    location: 'Pokhara',
    languages: ['Nepali', 'English'],
    fee: 'NPR 2,500 – 8,000',
    bio: 'Focuses on human rights violations, legal aid, and social justice cases.',
    phone: '+977-9800000009',
    email: 'roshan@lawmail.com',
    available: true,
  },
  {
    name: 'Adv. Anita Kafle',
    specialties: ['Family Law'],
    experience: 4,
    location: 'Bhaktapur',
    languages: ['Nepali'],
    fee: 'NPR 1,000 – 4,000',
    bio: 'Focuses on inheritance rights, adoption procedures, and domestic violence protection orders.',
    phone: '+977-9800000010',
    email: 'anita@lawmail.com',
    available: true,
  },
]

export async function POST() {
  await prisma.lawyer.deleteMany()
  const result = await prisma.lawyer.createMany({ data: SEED_LAWYERS })
  const lawyers = await prisma.lawyer.findMany({ orderBy: [{ available: 'desc' }, { experience: 'desc' }] })
  return Response.json({ seeded: result.count, lawyers }, { status: 201 })
}

export async function GET() {
  const count = await prisma.lawyer.count()
  return Response.json({ count, message: `${count} lawyers in database. POST to this endpoint to reseed.` })
}
