export interface Lawyer {
  id: number
  name: string
  specialization: string
  experience: string
  location: string
  languages: string[]
  feeRange: string
  rating: number
  casesHandled: number
  bio: string
  phone: string
  email: string
  featured: boolean
}

export const lawyers: Lawyer[] = [
  {
    id: 1,
    name: 'Adv. Priya Sharma',
    specialization: 'Family Law',
    experience: '8 years',
    location: 'Kathmandu',
    languages: ['Nepali', 'English', 'Hindi'],
    feeRange: 'NPR 2,000 – 6,000',
    rating: 4.9,
    casesHandled: 145,
    bio: 'Specializes in divorce, child custody, and property disputes within family matters.',
    phone: '+977-9800000001',
    email: 'priya@lawmail.com',
    featured: true,
  },
  {
    id: 2,
    name: 'Adv. Sushil Acharya',
    specialization: 'Criminal Law',
    experience: '14 years',
    location: 'Kathmandu',
    languages: ['Nepali', 'English'],
    feeRange: 'NPR 5,000 – 15,000',
    rating: 4.8,
    casesHandled: 230,
    bio: 'Experienced in criminal defense, bail hearings, and appellate proceedings across Bagmati courts.',
    phone: '+977-9800000002',
    email: 'sushil@lawmail.com',
    featured: true,
  },
  {
    id: 3,
    name: 'Adv. Bina Thapa',
    specialization: 'Business Law',
    experience: '6 years',
    location: 'Lalitpur',
    languages: ['Nepali', 'English'],
    feeRange: 'NPR 3,000 – 10,000',
    rating: 4.7,
    casesHandled: 88,
    bio: 'Advises startups and SMEs on company registration, contracts, and compliance with Nepal Company Act.',
    phone: '+977-9800000003',
    email: 'bina@lawmail.com',
    featured: true,
  },
  {
    id: 4,
    name: 'Adv. Rajan Poudel',
    specialization: 'Property Law',
    experience: '11 years',
    location: 'Pokhara',
    languages: ['Nepali'],
    feeRange: 'NPR 2,000 – 7,000',
    rating: 4.5,
    casesHandled: 178,
    bio: 'Handles land disputes, registration fraud, and property transfer cases in Gandaki Province.',
    phone: '+977-9800000004',
    email: 'rajan@lawmail.com',
    featured: false,
  },
  {
    id: 5,
    name: 'Adv. Kamala Gurung',
    specialization: 'Labour Law',
    experience: '9 years',
    location: 'Kathmandu',
    languages: ['Nepali', 'English'],
    feeRange: 'NPR 1,500 – 5,000',
    rating: 4.6,
    casesHandled: 112,
    bio: 'Represents workers in wrongful termination, wage disputes, and occupational safety cases.',
    phone: '+977-9800000005',
    email: 'kamala@lawmail.com',
    featured: false,
  },
  {
    id: 6,
    name: 'Adv. Dipesh Maharjan',
    specialization: 'Tax Law',
    experience: '7 years',
    location: 'Lalitpur',
    languages: ['Nepali', 'English'],
    feeRange: 'NPR 3,000 – 9,000',
    rating: 4.4,
    casesHandled: 63,
    bio: 'Assists businesses with VAT compliance, IRD disputes, and international tax matters.',
    phone: '+977-9800000006',
    email: 'dipesh@lawmail.com',
    featured: false,
  },
  {
    id: 7,
    name: 'Adv. Sunita Rai',
    specialization: 'Immigration Law',
    experience: '5 years',
    location: 'Kathmandu',
    languages: ['Nepali', 'English', 'Japanese'],
    feeRange: 'NPR 4,000 – 12,000',
    rating: 4.7,
    casesHandled: 74,
    bio: 'Handles visa applications, work permits, citizenship acquisition, and immigration appeals.',
    phone: '+977-9800000007',
    email: 'sunita@lawmail.com',
    featured: false,
  },
  {
    id: 8,
    name: 'Adv. Prakash Bhattarai',
    specialization: 'Criminal Law',
    experience: '18 years',
    location: 'Chitwan',
    languages: ['Nepali', 'English', 'Hindi'],
    feeRange: 'NPR 4,000 – 12,000',
    rating: 4.8,
    casesHandled: 310,
    bio: 'Senior criminal lawyer with extensive experience in high-profile cases and Supreme Court practice.',
    phone: '+977-9800000008',
    email: 'prakash@lawmail.com',
    featured: false,
  },
  {
    id: 9,
    name: 'Adv. Roshan Shahi',
    specialization: 'Human Rights Law',
    experience: '10 years',
    location: 'Pokhara',
    languages: ['Nepali', 'English'],
    feeRange: 'NPR 2,500 – 8,000',
    rating: 4.6,
    casesHandled: 90,
    bio: 'Focuses on human rights violations, legal aid, and social justice cases.',
    phone: '+977-9800000009',
    email: 'roshan@lawmail.com',
    featured: false,
  },
  {
    id: 10,
    name: 'Adv. Anita Kafle',
    specialization: 'Family Law',
    experience: '4 years',
    location: 'Bhaktapur',
    languages: ['Nepali'],
    feeRange: 'NPR 1,000 – 4,000',
    rating: 4.3,
    casesHandled: 47,
    bio: 'Focuses on inheritance rights, adoption procedures, and domestic violence protection orders.',
    phone: '+977-9800000010',
    email: 'anita@lawmail.com',
    featured: false,
  },
]

export const SPECIALIZATIONS = ['All', 'Criminal Law', 'Family Law', 'Business Law', 'Property Law', 'Human Rights Law', 'Labour Law', 'Tax Law', 'Immigration Law']
export const LOCATIONS = ['All', 'Kathmandu', 'Lalitpur', 'Bhaktapur', 'Pokhara', 'Chitwan']
export const RATINGS = [
  { label: 'Any rating', value: 0 },
  { label: '4+ stars', value: 4 },
  { label: '4.5+ stars', value: 4.5 },
  { label: '4.8+ stars', value: 4.8 },
]
